// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxiehrlepqrqquyrzjpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4aWVocmxlcHFycXF1eXJ6anB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjQ0NTYsImV4cCI6MjA2ODQ0MDQ1Nn0.G4-1g9Ti3aONfdYbpg2kQ7D8EmOy940aq0vPsAGpMQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});